### ISSUE TITLE
AOT compilation failed with ClassNotFoundException org.apache.http.nio.conn.ssl.SSLIOSessionStrategy

### ISSUE THREAD

**Issue by maxp** [amperity/vault-clj#56]
It works ok with 1.0.3 but crashes for 1.0.4.
[stack-trace.edn](https://github.com/amperity/vault-clj/files/6991395/1.txt)

**Comment by maxp** [comment]
1.0.5 - works well!
